parameters:
  configuration: 'Debug'
  
steps:
- pwsh: ./build.ps1 --configuration='${{ parameters.configuration }}'
  displayName: Build
- pwsh: ./build.ps1 --target=Test --skip-target='Build' --configuration='${{ parameters.configuration }}' --artifactsDir='$(Build.ArtifactStagingDirectory)'
  displayName: Run Tests
- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: always()
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/test-results/*.trx'
    failTaskOnFailedTests: true
    buildConfiguration: ${{ parameters.configuration }}
- task: PublishCodeCoverageResults@1
  displayName: Publish Coverage Results
  condition: always()
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/test-results/*.cobertura.xml'
