parameters:
  configuration: 'Debug'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ./install-steps.yml  
  - template: ./build-steps.yml
    parameters:
      configuration: $(configuration)
  - template: ./publish-steps.yml
    parameters:
      configuration: $(configuration)  

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: ./install-steps.yml  
  - template: ./build-steps.yml
    parameters:
      configuration: $(configuration)
      
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ./install-steps.yml  
  - template: ./build-steps.yml
    parameters:
      configuration: $(configuration)
